// <auto-generated />
using System;
using DongHoBlazorApp.Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DongHoBlazorApp.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260205085753_AddTableDongHoBLPNCTPN")]
    partial class AddTableDongHoBLPNCTPN
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DongHoBlazorApp.Model.Entities.BinhLuanModel", b =>
                {
                    b.Property<int>("MaBL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBL"));

                    b.Property<int>("MaDongHo")
                        .HasColumnType("int");

                    b.Property<int>("MaThanhVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBinhLuan")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungBL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThanhVien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaBL");

                    b.HasIndex("MaDongHo");

                    b.ToTable("BinhLuans");
                });

            modelBuilder.Entity("DongHoBlazorApp.Model.Entities.ChiTietPhieuNhapModel", b =>
                {
                    b.Property<int>("MaChiTietPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietPhieuNhap"));

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDongHo")
                        .HasColumnType("int");

                    b.Property<int>("MaPhieuNhap")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietPhieuNhap");

                    b.HasIndex("MaDongHo");

                    b.HasIndex("MaPhieuNhap");

                    b.ToTable("ChiTietPhieuNhapModels");
                });

            modelBuilder.Entity("DongHoBlazorApp.Model.Entities.DongHoModel", b =>
                {
                    b.Property<int>("MaDongHo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDongHo"));

                    b.Property<int>("DaBan")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LuotBinhLuan")
                        .HasColumnType("int");

                    b.Property<int>("LuotXem")
                        .HasColumnType("int");

                    b.Property<int>("MaNCC")
                        .HasColumnType("int");

                    b.Property<int>("MaPL")
                        .HasColumnType("int");

                    b.Property<int>("MaThuongHieu")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenDongHo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDongHo");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaPL");

                    b.HasIndex("MaThuongHieu");

                    b.ToTable("DongHos");
                });

            modelBuilder.Entity("DongHoBlazorApp.Model.Entities.NhaCungCapModel", b =>
                {
                    b.Property<int>("MaNCC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNCC"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Email")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenNCC")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaNCC");

                    b.ToTable("NhaCungCaps");
                });

            modelBuilder.Entity("DongHoBlazorApp.Model.Entities.PhanLoaiModel", b =>
                {
                    b.Property<int>("MaPL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPL"));

                    b.Property<string>("TenPL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaPL");

                    b.ToTable("PhanLoais");
                });

            modelBuilder.Entity("DongHoBlazorApp.Model.Entities.PhieuNhapModel", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuNhap"));

                    b.Property<int>("MaNCC")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaPhieuNhap");

                    b.HasIndex("MaNCC");

                    b.ToTable("PhieuNhaps");
                });

            modelBuilder.Entity("DongHoBlazorApp.Model.Entities.ThuongHieuModel", b =>
                {
                    b.Property<int>("MaThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThuongHieu"));

                    b.Property<string>("Logo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThuongHieu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaThuongHieu");

                    b.ToTable("ThuongHieus");
                });

            modelBuilder.Entity("DongHoBlazorApp.Model.Entities.BinhLuanModel", b =>
                {
                    b.HasOne("DongHoBlazorApp.Model.Entities.DongHoModel", null)
                        .WithMany()
                        .HasForeignKey("MaDongHo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DongHoBlazorApp.Model.Entities.ChiTietPhieuNhapModel", b =>
                {
                    b.HasOne("DongHoBlazorApp.Model.Entities.DongHoModel", null)
                        .WithMany()
                        .HasForeignKey("MaDongHo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DongHoBlazorApp.Model.Entities.PhieuNhapModel", null)
                        .WithMany()
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DongHoBlazorApp.Model.Entities.DongHoModel", b =>
                {
                    b.HasOne("DongHoBlazorApp.Model.Entities.NhaCungCapModel", null)
                        .WithMany()
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DongHoBlazorApp.Model.Entities.PhanLoaiModel", null)
                        .WithMany()
                        .HasForeignKey("MaPL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DongHoBlazorApp.Model.Entities.ThuongHieuModel", null)
                        .WithMany()
                        .HasForeignKey("MaThuongHieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DongHoBlazorApp.Model.Entities.PhieuNhapModel", b =>
                {
                    b.HasOne("DongHoBlazorApp.Model.Entities.NhaCungCapModel", null)
                        .WithMany()
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
